### ISSUE TITLE
Library not very robust to behavior of devices in the wild

### ISSUE THREAD

**Issue by solenskiner** [xinhuang/pyupnp-async#2]
Hello, 

I tried to use this, but ran in to a bunch of issues.

> Exception in callback _SelectorDatagramTransport._read_ready()
> handle: <Handle _SelectorDatagramTransport._read_ready()>
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/lib64/python3.6/asyncio/selector_events.py", line 1077, in _read_ready
>     self._protocol.datagram_received(data, addr)
>   File "/home/floyd/projects/malmö/lib/python3.6/site-packages/pyupnp_async/upnp.py", line 67, in datagram_received
>     self.responses.put_nowait(MSResponse(addr, data.decode()))
>   File "/home/floyd/projects/malmö/lib/python3.6/site-packages/pyupnp_async/upnp.py", line 24, in __init__
>     self.st = data['ST']
> KeyError: 'ST'

Uncommenting that lead to

> Exception in callback _SelectorDatagramTransport._read_ready()
> handle: <Handle _SelectorDatagramTransport._read_ready()>
> Traceback (most recent call last):
>   File "/usr/lib64/python3.6/asyncio/events.py", line 145, in _run
>     self._callback(*self._args)
>   File "/usr/lib64/python3.6/asyncio/selector_events.py", line 1077, in _read_ready
>     self._protocol.datagram_received(data, addr)
>   File "/home/floyd/projects/malmö/lib/python3.6/site-packages/pyupnp_async/upnp.py", line 67, in datagram_received
>     self.responses.put_nowait(MSResponse(addr, data.decode()))
>   File "/home/floyd/projects/malmö/lib/python3.6/site-packages/pyupnp_async/upnp.py", line 26, in __init__
>     self.server = data['SERVER']
> KeyError: 'SERVER'

because the key name as returned by the router was not SERVER, but Server. Fixed with call to msg.lower() and changing key names. In the Service class i got a keyerror on u:getexternalipaddressresponse, my router had returned m:getexternalipaddressresponse instead.

Thats when I stopped playing bug whack-a-mole. 

Are you interested in fixing issues like these ones, or should i find another library?

**Comment by xinhuang** [comment]
Sorry that I only tried with router Netgear 6300v2. If you are looking for a good UPnP library, try libupnp.

**Comment by dgomes** [comment]
Sorry to reopen this issue

I've created a PR that solves this:

https://github.com/xinhuang/pyupnp-async/pull/5
